**

!package.json
!package-lock.json
!tsconfig.base.json
!spec-source/
!spec-source/**
!protocol/
!protocol/**
!runtime/
!runtime/**
!distribution/
!distribution/package/
!distribution/package/package.json
!third-party/
!third-party/atlas-reference-validator/
!third-party/atlas-reference-validator/PROVENANCE.json
!third-party/atlas-reference-validator/LICENSE
!third-party/atlas-reference-validator/package/
!third-party/atlas-reference-validator/package/**

**/node_modules/
**/dist/
**/*.tgz
**/.env
**/.env.*
**/*.log
**/.DS_Store
